name: Build Snapshot

on:
  push:
    branches:
      - 'master'

jobs:
  build_Linux:
    name: Build Windows/Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          RELEASE: false

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Check Ant
        run: ant -version

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Generate Native Project
        run: ./gradlew generateNativeProject

      - name: Upload to repository
        run: ./gradlew publish
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          signingKey: ${{ secrets.PGP_SECRET }}
          signingPassword: ${{ secrets.PGP_PASSPHRASE }}